[Unit]
After=pipewire.service wireplumber.service
Wants=pipewire.service wireplumber.service

[Service]
Environment=PIPEWIRE_RUNTIME_DIR=/run/pipewire
Environment=GST_AUDIO_SINK=bin.( audioconvert ! audioresample ! pipewiresink target-object=ivi_hdmi_sink )
Environment=GST_DEFAULT_SINK=bin.( audioconvert ! audioresample ! pipewiresink target-object=ivi_hdmi_sink )
