# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-custom-rpi5"
BBFILE_PATTERN_meta-custom-rpi5 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-custom-rpi5 = "10"

LAYERDEPENDS_meta-custom-rpi5 = "core openembedded-layer raspberrypi qt6-layer"
LAYERSERIES_COMPAT_meta-custom-rpi5 = "scarthgap"
